-- =========================================================================
-- MASHAAL PETROLEUM — RESET TO A BLANK SYSTEM        *** CANNOT BE UNDONE ***
-- Generated by scripts/build-sql.mjs.
--
-- DELETES every record of SITE-01 and SITE-02: sales, dips, customers, slips, receipts, cash book,
-- expenses, OMC invoices, bank accounts and lines, staff and payroll, lubricants, suppliers, tanks, nozzles,
-- the audit trail and the document numbers. It also DROPS the old archive tables (legacy_*).
--
-- KEPT: the station list, all login accounts, the station settings row (fuel prices, dealer margins,
-- alert limits) and the migration log (so setup.sql can never bring the old data back).
--
-- Only run this after you have saved a backup. It runs as ONE transaction: if anything fails, nothing changes.
-- =========================================================================
begin;

-- SITE-01 (s01_*)
truncate table
  public.s01_tanks,
  public.s01_nozzles,
  public.s01_fuel_sales,
  public.s01_shifts,
  public.s01_tank_dips,
  public.s01_omc_invoices,
  public.s01_omc_payments,
  public.s01_bank_accounts,
  public.s01_bank_transactions,
  public.s01_owner_transfers,
  public.s01_daybook_entries,
  public.s01_customers,
  public.s01_credit_slips,
  public.s01_customer_recoveries,
  public.s01_customer_adjustments,
  public.s01_expenses,
  public.s01_staff_members,
  public.s01_staff_advances,
  public.s01_staff_salary_payments,
  public.s01_lubricant_products,
  public.s01_lubricant_movements,
  public.s01_suppliers,
  public.s01_supplier_transactions,
  public.s01_tariff_revisions,
  public.s01_audit_log,
  public.s01_doc_counters
restart identity cascade;

-- SITE-02 (s02_*)
truncate table
  public.s02_tanks,
  public.s02_nozzles,
  public.s02_fuel_sales,
  public.s02_shifts,
  public.s02_tank_dips,
  public.s02_omc_invoices,
  public.s02_omc_payments,
  public.s02_bank_accounts,
  public.s02_bank_transactions,
  public.s02_owner_transfers,
  public.s02_daybook_entries,
  public.s02_customers,
  public.s02_credit_slips,
  public.s02_customer_recoveries,
  public.s02_customer_adjustments,
  public.s02_expenses,
  public.s02_staff_members,
  public.s02_staff_advances,
  public.s02_staff_salary_payments,
  public.s02_lubricant_products,
  public.s02_lubricant_movements,
  public.s02_suppliers,
  public.s02_supplier_transactions,
  public.s02_tariff_revisions,
  public.s02_audit_log,
  public.s02_doc_counters
restart identity cascade;

-- the old archive (renamed legacy_* tables)
do $$
declare r record;
begin
  for r in select tablename from pg_tables where schemaname = 'public' and tablename like 'legacy\_%' loop
    execute format('drop table public.%I cascade', r.tablename);
  end loop;
end $$;

commit;

-- RESULT: every count below should be 0 (settings = 1 per station)
select 'ALL' as station, 'login accounts (kept)' as item, count(*) as value from public.profiles
union all select 'SITE-01', 'customers', count(*) from public.s01_customers
union all select 'SITE-01', 'tanks', count(*) from public.s01_tanks
union all select 'SITE-01', 'daybook entries', count(*) from public.s01_daybook_entries
union all select 'SITE-01', 'fuel sales', count(*) from public.s01_fuel_sales
union all select 'SITE-01', 'settings row (kept)', count(*) from public.s01_station_settings
union all select 'SITE-02', 'customers', count(*) from public.s02_customers
union all select 'SITE-02', 'tanks', count(*) from public.s02_tanks
union all select 'SITE-02', 'daybook entries', count(*) from public.s02_daybook_entries
union all select 'SITE-02', 'fuel sales', count(*) from public.s02_fuel_sales
union all select 'SITE-02', 'settings row (kept)', count(*) from public.s02_station_settings
union all select 'ALL', 'old archive tables left', count(*) from pg_tables where schemaname = 'public' and tablename like 'legacy\_%';
