-- =========================================================================
-- MASHAAL PETROLEUM — UPDATE (adds new columns and refreshes the save function; no data is changed or removed)
-- Generated by scripts/build-sql.mjs. Run once in Supabase -> SQL Editor. Safe to run again.
-- =========================================================================
alter table public.s01_customer_recoveries   add column if not exists bank_pending   boolean not null default false;
alter table public.s01_staff_salary_payments add column if not exists deduction      numeric not null default 0;
alter table public.s01_staff_salary_payments add column if not exists absent_days    numeric not null default 0;
alter table public.s01_staff_salary_payments add column if not exists deduction_note text;
alter table public.s01_supplier_transactions add column if not exists source_type    text;
alter table public.s01_supplier_transactions add column if not exists source_id      text;

alter table public.s02_customer_recoveries   add column if not exists bank_pending   boolean not null default false;
alter table public.s02_staff_salary_payments add column if not exists deduction      numeric not null default 0;
alter table public.s02_staff_salary_payments add column if not exists absent_days    numeric not null default 0;
alter table public.s02_staff_salary_payments add column if not exists deduction_note text;
alter table public.s02_supplier_transactions add column if not exists source_type    text;
alter table public.s02_supplier_transactions add column if not exists source_id      text;

-- the save function: an edit is refused when someone else changed the record in the meantime
-- APPLY_OPS-BEGIN
create or replace function public.apply_ops(p_site text, p_ops jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_allowed constant text[] := array[
    'station_settings', 'tanks', 'nozzles', 'fuel_sales', 'shifts', 'tank_dips',
    'omc_invoices', 'omc_payments', 'bank_accounts', 'bank_transactions', 'owner_transfers',
    'daybook_entries', 'customers', 'credit_slips', 'customer_recoveries', 'customer_adjustments',
    'expenses', 'staff_members', 'staff_advances', 'staff_salary_payments',
    'lubricant_products', 'lubricant_movements', 'suppliers', 'supplier_transactions',
    'tariff_revisions', 'audit_log'
  ];
  v_prefix text;
  v_op     jsonb;
  v_t      text;
  v_full   text;
  v_a      text;
  v_row    jsonb;
  v_id     text;
  v_cols   text;
  v_set    text;
  v_res    jsonb;
  v_ver    text;
  v_exists boolean;
  v_out    jsonb := '[]'::jsonb;
begin
  if p_site is null or p_site = '' then
    raise exception 'apply_ops: station is required';
  end if;
  select s.table_prefix into v_prefix from public.stations s where s.site_id = p_site;
  if v_prefix is null then
    raise exception 'apply_ops: unknown station "%"', p_site;
  end if;
  if p_ops is null or jsonb_typeof(p_ops) <> 'array' then
    raise exception 'apply_ops: ops must be a JSON array';
  end if;
  if jsonb_array_length(p_ops) > 20000 then
    raise exception 'apply_ops: too many operations in one call';
  end if;

  for v_op in select value from jsonb_array_elements(p_ops) loop
    v_t := v_op ->> 't';
    v_a := v_op ->> 'a';
    if v_t is null or not (v_t = any (v_allowed)) then
      raise exception 'apply_ops: table "%" is not writable', coalesce(v_t, '(null)');
    end if;
    v_full := v_prefix || '_' || v_t;

    v_row := coalesce(v_op -> 'row', '{}'::jsonb) - 'site_id';
    v_id  := v_row ->> 'id';
    v_res := null;

    if v_a in ('insert', 'insert_ignore', 'upsert') then
      select string_agg(quote_ident(k), ', ') into v_cols from jsonb_object_keys(v_row) as k;
      select string_agg(quote_ident(k), ', ') into v_set
        from jsonb_object_keys(v_row) as k where k <> 'id';
      if v_cols is null then
        raise exception 'apply_ops: % needs a row', v_a;
      end if;

      if v_a = 'insert' then
        execute format(
          'insert into public.%1$I as t (%2$s) select %2$s from jsonb_populate_record(null::public.%1$I, $1) returning to_jsonb(t.*)',
          v_full, v_cols) into v_res using v_row;
      elsif v_a = 'insert_ignore' or v_set is null then
        execute format(
          'insert into public.%1$I as t (%2$s) select %2$s from jsonb_populate_record(null::public.%1$I, $1) on conflict (id) do nothing returning to_jsonb(t.*)',
          v_full, v_cols) into v_res using v_row;
      else
        execute format(
          'insert into public.%1$I as t (%2$s) select %2$s from jsonb_populate_record(null::public.%1$I, $1) '
          'on conflict (id) do update set (%3$s) = (select %3$s from jsonb_populate_record(null::public.%1$I, $1)) '
          'returning to_jsonb(t.*)',
          v_full, v_cols, v_set) into v_res using v_row;
      end if;

      if v_res is not null then
        v_out := v_out || jsonb_build_array(jsonb_build_object('t', v_t, 'a', 'upsert', 'row', v_res));
      end if;

    elsif v_a = 'update' then
      if v_id is null then
        raise exception 'apply_ops: update on "%" needs an id', v_t;
      end if;
      select string_agg(quote_ident(k), ', ') into v_set
        from jsonb_object_keys(v_row) as k where k <> 'id';
      if v_set is null then
        continue;
      end if;
      -- optional edit check: "v" is the version (updated_at) of the record as the person saw it when they opened it
      v_ver := nullif(v_op ->> 'v', '');
      if v_ver is null then
        execute format(
          'update public.%1$I as t set (%2$s) = (select %2$s from jsonb_populate_record(null::public.%1$I, $1)) '
          'where t.id = $2 returning to_jsonb(t.*)',
          v_full, v_set) into v_res using v_row, v_id;
      else
        execute format(
          'update public.%1$I as t set (%2$s) = (select %2$s from jsonb_populate_record(null::public.%1$I, $1)) '
          'where t.id = $2 and t.updated_at = $3::timestamptz returning to_jsonb(t.*)',
          v_full, v_set) into v_res using v_row, v_id, v_ver;
      end if;
      if v_res is null then
        if v_ver is not null then
          execute format('select exists (select 1 from public.%I where id = $1)', v_full) into v_exists using v_id;
          if v_exists then
            raise exception using errcode = 'P0409',
              message = 'This record was changed by someone else while you had it open. Nothing was saved. Close this window, open the record again to see their change, then redo yours.';
          end if;
        end if;
        raise exception 'apply_ops: % "%" was not found (or you do not have permission to change it)', v_t, v_id;
      end if;
      v_out := v_out || jsonb_build_array(jsonb_build_object('t', v_t, 'a', 'upsert', 'row', v_res));

    elsif v_a = 'delete' then
      if v_id is null then
        raise exception 'apply_ops: delete on "%" needs an id', v_t;
      end if;
      execute format('delete from public.%I where id = $1', v_full) using v_id;
      v_out := v_out || jsonb_build_array(jsonb_build_object('t', v_t, 'a', 'delete', 'row', jsonb_build_object('id', v_id)));

    elsif v_a = 'purge' then
      execute format('delete from public.%I', v_full);
      v_out := v_out || jsonb_build_array(jsonb_build_object('t', v_t, 'a', 'purge'));

    else
      raise exception 'apply_ops: unknown action "%"', coalesce(v_a, '(null)');
    end if;
  end loop;

  return v_out;
end $$;

select 'update applied' as result;
