-- =========================================================================
-- MASHAAL PETROLEUM — UPDATE (adds the new columns; no data is changed or removed)
-- Generated by scripts/build-sql.mjs. Run once in Supabase -> SQL Editor. Safe to run again.
-- =========================================================================
alter table public.s01_customer_recoveries   add column if not exists bank_pending   boolean not null default false;
alter table public.s01_staff_salary_payments add column if not exists deduction      numeric not null default 0;
alter table public.s01_staff_salary_payments add column if not exists absent_days    numeric not null default 0;
alter table public.s01_staff_salary_payments add column if not exists deduction_note text;
alter table public.s01_supplier_transactions add column if not exists source_type    text;
alter table public.s01_supplier_transactions add column if not exists source_id      text;

alter table public.s02_customer_recoveries   add column if not exists bank_pending   boolean not null default false;
alter table public.s02_staff_salary_payments add column if not exists deduction      numeric not null default 0;
alter table public.s02_staff_salary_payments add column if not exists absent_days    numeric not null default 0;
alter table public.s02_staff_salary_payments add column if not exists deduction_note text;
alter table public.s02_supplier_transactions add column if not exists source_type    text;
alter table public.s02_supplier_transactions add column if not exists source_id      text;

select 'update applied' as result;
