// Builds the one-file setup script that is pasted into the Supabase SQL Editor.
//   node scripts/build-sql.mjs                      -> supabase/setup.sql
//   node scripts/build-sql.mjs --add-station SITE-03 s03 "Station name" "Location" "BRAND"
//                                                   -> supabase/add_station_SITE-03.sql
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const parts = (f) => readFileSync(join(root, 'supabase', 'parts', f), 'utf8')

export const STATIONS = [
  { site: 'SITE-01', p: 's01' },
  { site: 'SITE-02', p: 's02' },
]

const expand = (tpl, { site, p }) =>
  tpl.replaceAll('{site_q}', `''${site}''`).replaceAll('{site}', `'${site}'`).replaceAll('{p}', p)

export function buildSetupSql() {
  const out = []
  out.push(`-- =========================================================================
-- MASHAAL PETROLEUM — COMPLETE SUPABASE SETUP + DATA MIGRATION
-- Generated by scripts/build-sql.mjs — do not edit by hand (edit supabase/parts/*).
--
-- WHEN TO USE IT: for a BRAND-NEW Supabase project only. For a system that is already
-- in use, run supabase/update.sql instead (see UPDATING.md).
--
-- HOW TO RUN: Supabase Dashboard -> SQL Editor -> New query -> paste this whole
-- file -> Run. Running it again does not delete data and does not recreate default
-- accounts. The final result table lists what was migrated so you can check it.
--
-- What it does, in order:
--   1. archives the old tables (renamed legacy_*, nothing is deleted) and closes
--      their open-access policies
--   2. creates the shared tables (station list, logins)
--   3. creates the functions (access rules, atomic writes, document numbers, user admin)
--   4. creates SEPARATE table sets per station (${STATIONS.map((s) => `${s.site} = ${s.p}_*`).join(', ')})
--      with row-level security
--   5. migrates every record from the old data into the new tables
--   6. creates the login accounts
-- =========================================================================
`)
  out.push(parts('10_archive_legacy.sql'))
  out.push(parts('15_global.sql'))
  out.push(parts('30_functions.sql'))
  for (const s of STATIONS) out.push(expand(parts('20_station_schema.tpl.sql'), s))
  out.push(parts('40_global_policies.sql'))
  for (const s of STATIONS) out.push(expand(parts('50_migrate_legacy.tpl.sql'), s))
  out.push(parts('60_seed_users.sql'))
  const frag = STATIONS.map((s) => expand(parts('70_verify_fragment.tpl.sql'), s).trim()).join('\nunion all\n')
  out.push(`-- =========================================================================
-- RESULT: what is now in the database (compare with your old data)
-- =========================================================================
select * from (
${frag}
union all select 'ALL', 'login accounts', count(*) from public.profiles
) as summary
order by station, item;
`)
  return out.join('\n')
}

/** Only the columns added after the first release — a small script for a database that is already set up. */
export function buildUpdateSql() {
  const tpl = parts('20_station_schema.tpl.sql')
  const block = tpl.slice(tpl.indexOf('-- UPGRADES-BEGIN'), tpl.indexOf('-- UPGRADES-END')).replace('-- UPGRADES-BEGIN\n', '')
  const fn = parts('30_functions.sql')
  const applyOps = fn.slice(fn.indexOf('-- APPLY_OPS-BEGIN'), fn.indexOf('-- APPLY_OPS-END')).replace('-- APPLY_OPS-BEGIN\n', '')
  return `-- =========================================================================
-- MASHAAL PETROLEUM — UPDATE (adds new columns and refreshes the save function; no data is changed or removed)
-- Generated by scripts/build-sql.mjs. Run once in Supabase -> SQL Editor. Safe to run again.
-- =========================================================================
${STATIONS.map((s) => expand(block, s).trim()).join('\n\n')}

-- the save function: an edit is refused when someone else changed the record in the meantime
${applyOps.trim()}

select 'update applied' as result;
`
}

/** Every station table that holds records (everything except the settings row and the number counters). */
export function stationTables() {
  const tpl = parts('20_station_schema.tpl.sql')
  return [...new Set([...tpl.matchAll(/create table if not exists public\.\{p\}_([a-z_]+)/g)].map((m) => m[1]))]
    .filter((t) => t !== 'station_settings')
}

/**
 * DANGEROUS by design: empties the whole system. Every record of every station is deleted (customers, staff,
 * tanks, nozzles, banks ... included) and the old archive (legacy_*) is dropped. Kept: the stations, the login
 * accounts, the station settings row (prices, margins, alert limits) and the migration log.
 */
export function buildResetSql() {
  const list = stationTables()
  const blocks = STATIONS.map((s) => {
    const names = list.map((t) => `  public.${s.p}_${t}`).join(',\n')
    return `-- ${s.site} (${s.p}_*)\ntruncate table\n${names}\nrestart identity cascade;`
  })
  return `-- =========================================================================
-- MASHAAL PETROLEUM — RESET TO A BLANK SYSTEM        *** CANNOT BE UNDONE ***
-- Generated by scripts/build-sql.mjs.
--
-- DELETES every record of ${STATIONS.map((s) => s.site).join(' and ')}: sales, dips, customers, slips, receipts, cash book,
-- expenses, OMC invoices, bank accounts and lines, staff and payroll, lubricants, suppliers, tanks, nozzles,
-- the audit trail and the document numbers. It also DROPS the old archive tables (legacy_*).
--
-- KEPT: the station list, all login accounts, the station settings row (fuel prices, dealer margins,
-- alert limits) and the migration log (so setup.sql can never bring the old data back).
--
-- Only run this after you have saved a backup. It runs as ONE transaction: if anything fails, nothing changes.
-- =========================================================================
begin;

${blocks.join('\n\n')}

-- the old archive (renamed legacy_* tables)
do $$
declare r record;
begin
  for r in select tablename from pg_tables where schemaname = 'public' and tablename like 'legacy\\_%' loop
    execute format('drop table public.%I cascade', r.tablename);
  end loop;
end $$;

commit;

-- RESULT: every count below should be 0 (settings = 1 per station)
select 'ALL' as station, 'login accounts (kept)' as item, count(*) as value from public.profiles
${STATIONS.map((s) => `union all select '${s.site}', 'customers', count(*) from public.${s.p}_customers
union all select '${s.site}', 'tanks', count(*) from public.${s.p}_tanks
union all select '${s.site}', 'daybook entries', count(*) from public.${s.p}_daybook_entries
union all select '${s.site}', 'fuel sales', count(*) from public.${s.p}_fuel_sales
union all select '${s.site}', 'settings row (kept)', count(*) from public.${s.p}_station_settings`).join('\n')}
union all select 'ALL', 'old archive tables left', count(*) from pg_tables where schemaname = 'public' and tablename like 'legacy\\_%';
`
}

export function buildAddStationSql(site, prefix, name, location, brand) {
  const s = { site, p: prefix }
  const q = (v) => `'${String(v).replaceAll("'", "''")}'`
  return `-- Adds station ${site} (tables ${prefix}_*). Run once in the Supabase SQL Editor.
insert into public.stations (site_id, table_prefix, code, name, location, brand)
values (${q(site)}, ${q(prefix)}, ${q(site.replace('-', ' '))}, ${q(name)}, ${q(location)}, ${q(brand)})
on conflict (site_id) do nothing;

${expand(parts('20_station_schema.tpl.sql'), s)}
`
}

if (process.argv[1] && process.argv[1].endsWith('build-sql.mjs')) {
  const args = process.argv.slice(2)
  if (args[0] === '--add-station') {
    const [, site, prefix, name, location, brand] = args
    if (!site || !prefix || !name) throw new Error('usage: --add-station SITE-03 s03 "Name" "Location" "BRAND"')
    writeFileSync(join(root, 'supabase', `add_station_${site}.sql`), buildAddStationSql(site, prefix, name, location ?? '', brand ?? 'PSO'))
    console.log(`wrote supabase/add_station_${site}.sql`)
  } else if (args[0] === '--reset-blank') {
    // the wipe-everything script is NEVER written inside the project, so it cannot be pasted in by accident
    const target = resolve(args[1] ?? '')
    if (!args[1] || relative(root, target) === '' || !relative(root, target).startsWith('..')) {
      throw new Error('usage: node scripts/build-sql.mjs --reset-blank "C:/somewhere/OUTSIDE/the/project/reset_blank.sql"')
    }
    writeFileSync(target, buildResetSql())
    console.log(`wrote ${target} — this script DELETES ALL DATA. Keep it away from the project.`)
  } else {
    const sql = buildSetupSql()
    writeFileSync(join(root, 'supabase', 'setup.sql'), sql)
    console.log(`wrote supabase/setup.sql (${sql.length} bytes)`)
    const update = buildUpdateSql()
    writeFileSync(join(root, 'supabase', 'update.sql'), update)
    console.log(`wrote supabase/update.sql (${update.length} bytes)`)
  }
}
