// Builds the one-file setup script that is pasted into the Supabase SQL Editor.
//   node scripts/build-sql.mjs                      -> supabase/setup.sql
//   node scripts/build-sql.mjs --add-station SITE-03 s03 "Station name" "Location" "BRAND"
//                                                   -> supabase/add_station_SITE-03.sql
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const parts = (f) => readFileSync(join(root, 'supabase', 'parts', f), 'utf8')

export const STATIONS = [
  { site: 'SITE-01', p: 's01' },
  { site: 'SITE-02', p: 's02' },
]

const expand = (tpl, { site, p }) =>
  tpl.replaceAll('{site_q}', `''${site}''`).replaceAll('{site}', `'${site}'`).replaceAll('{p}', p)

export function buildSetupSql() {
  const out = []
  out.push(`-- =========================================================================
-- MASHAAL PETROLEUM — COMPLETE SUPABASE SETUP + DATA MIGRATION
-- Generated by scripts/build-sql.mjs — do not edit by hand (edit supabase/parts/*).
--
-- HOW TO RUN: Supabase Dashboard -> SQL Editor -> New query -> paste this whole
-- file -> Run. It is safe to run more than once. The final result table lists what
-- was migrated so you can check it against what you had.
--
-- What it does, in order:
--   1. archives the old tables (renamed legacy_*, nothing is deleted) and closes
--      their open-access policies
--   2. creates the shared tables (station list, logins)
--   3. creates the functions (access rules, atomic writes, document numbers, user admin)
--   4. creates SEPARATE table sets per station (${STATIONS.map((s) => `${s.site} = ${s.p}_*`).join(', ')})
--      with row-level security
--   5. migrates every record from the old data into the new tables
--   6. creates the login accounts
-- =========================================================================
`)
  out.push(parts('10_archive_legacy.sql'))
  out.push(parts('15_global.sql'))
  out.push(parts('30_functions.sql'))
  for (const s of STATIONS) out.push(expand(parts('20_station_schema.tpl.sql'), s))
  out.push(parts('40_global_policies.sql'))
  for (const s of STATIONS) out.push(expand(parts('50_migrate_legacy.tpl.sql'), s))
  out.push(parts('60_seed_users.sql'))
  const frag = STATIONS.map((s) => expand(parts('70_verify_fragment.tpl.sql'), s).trim()).join('\nunion all\n')
  out.push(`-- =========================================================================
-- RESULT: what is now in the database (compare with your old data)
-- =========================================================================
select * from (
${frag}
union all select 'ALL', 'login accounts', count(*) from public.profiles
) as summary
order by station, item;
`)
  return out.join('\n')
}

export function buildAddStationSql(site, prefix, name, location, brand) {
  const s = { site, p: prefix }
  const q = (v) => `'${String(v).replaceAll("'", "''")}'`
  return `-- Adds station ${site} (tables ${prefix}_*). Run once in the Supabase SQL Editor.
insert into public.stations (site_id, table_prefix, code, name, location, brand)
values (${q(site)}, ${q(prefix)}, ${q(site.replace('-', ' '))}, ${q(name)}, ${q(location)}, ${q(brand)})
on conflict (site_id) do nothing;

${expand(parts('20_station_schema.tpl.sql'), s)}
`
}

if (process.argv[1] && process.argv[1].endsWith('build-sql.mjs')) {
  const args = process.argv.slice(2)
  if (args[0] === '--add-station') {
    const [, site, prefix, name, location, brand] = args
    if (!site || !prefix || !name) throw new Error('usage: --add-station SITE-03 s03 "Name" "Location" "BRAND"')
    writeFileSync(join(root, 'supabase', `add_station_${site}.sql`), buildAddStationSql(site, prefix, name, location ?? '', brand ?? 'PSO'))
    console.log(`wrote supabase/add_station_${site}.sql`)
  } else {
    const sql = buildSetupSql()
    writeFileSync(join(root, 'supabase', 'setup.sql'), sql)
    console.log(`wrote supabase/setup.sql (${sql.length} bytes)`)
  }
}
